<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>Foro Oficial de BoomBang! &bull; Index page</title>



<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/esp/forum; domain=boombang.tv';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	

	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/boombang/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/boombang/template/forum_fn.js"></script>

<link href="./styles/boombang/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?id=4&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/boombang/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/boombang/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/boombang/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />



<script src="http://cdn.publicidad.net/library/boombang/generic.js"></script> 

<script type="text/javascript">

	function countAdClick(id)
	{
	   loadXMLDoc('./ads/click.php?a=' + id);
	}

	function countAdView(id)
	{
	   loadXMLDoc('./ads/view.php?a=' + id);
	}

	function loadXMLDoc(url) {
	   req = false;
	   if(window.XMLHttpRequest) {
	      try {
	         req = new XMLHttpRequest();
	      } catch(e) {
	         req = false;
	      }
	   } else if(window.ActiveXObject) {
	      try {
	         req = new ActiveXObject("Msxml2.XMLHTTP");
	      } catch(e) {
	         try {
	            req = new ActiveXObject("Microsoft.XMLHTTP");
	         } catch(e) {
	            req = false;
	         }
	      }
	   }
	   if(req) {
	      req.open("GET", url, true);
	      req.send(null);
	   }
	}
</script>

<script type="text/javascript" charset="utf-8">
	function popUp(URL)
	{
	  var options = "";
	  var direccion= URL;
	  {
	    var w = screen.width;
	    var h = screen.height;
	    var winw = 1012;
	    var winh = 657;
	    var winl = (w - winw)/2;
	    var wint = (h -winh)/2;
	    options="toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+winw+",height="+winh+",left="+winl+",top ="+wint;
	   }
	   var win = window.open(direccion, 'BoomBang', options);
	}
</script>

<link href='http://fonts.googleapis.com/css?family=Nunito:400,700' rel='stylesheet' type='text/css'>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1615984-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>

<body id="phpbb" class="section-index ltr">

<script src="http://cdn.publicidad.net/library/boombang/portada/dhtml.js"></script> 

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		
		
		
		<div class="headerbar">
			
			<div class="header_background">
				
				<div id="site-description">
					<a href="./index.php" title="Board index" id="logo"><img src="./styles/boombang/imageset/boombang_logo-es.png" width="239" height="163" alt="" title="" /></a>
					<h1>Foro Oficial de BoomBang!</h1>
					<p></p>
					<p class="skiplink"><a href="#start_here">Skip to content</a></p>
				</div>
				
				<div class="header_content">
					
					<a class="buttons" id="link_play" href="" onclick="javascript: return popUp('http://boombang.tv/esp/play/')"><span></span></a>
					
							
					<div class="header_banner">
						<div class="banner_container">
						<script src='http://cdn.publicidad.net/library/boombang/interior/728x90.js' >
</script>
						</div>
					</div>
					
				</div>
				
			</div>
			
		</div>

		
		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks">
				<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a> </li>

				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="return fontsizeup(event);" class="fontsize" title="Change font size">Change font size</a></li>

				
			</ul>

			

			<ul class="linklist rightside">
				<li class="icon-faq"><a href="./faq.php" title="Frequently Asked Questions">FAQ</a></li>
				
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
		

	</div>
	
	<a name="start_here"></a>
	<div id="page-body">
		
		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=26">Mundo BB</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=14" class="forumtitle">General</a><br />
					Aquí podrás hablar sobre todo lo que se te ocurra. Comparte tus experiencias en BoomBang.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">9467 <dfn>Topics</dfn></dd>
					<dd class="posts">87295 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by panchitoasko
						<br />Fri Jan 17, 2014 9:34 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=21" class="forumtitle">Preséntate</a><br />
					¿Eres nuevo en BoomBang? ¿Quieres que todos te conozcan? Entra y preséntate.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">1458 <dfn>Topics</dfn></dd>
					<dd class="posts">8126 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by pedrohx
						<br />Fri Jan 17, 2014 7:58 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=51" class="forumtitle">Eventos</a><br />
					Consulta las bases de los concursos y eventos activos en el Foro, ¡y no olvides inscribirte! Los ganadores aparecerán en el ranking y se llevarán objetos de BoomBang.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">68 <dfn>Topics</dfn></dd>
					<dd class="posts">2823 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by emavsema
						<br />Tue Jan 14, 2014 4:08 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=20" class="forumtitle">Noticias</a><br />
					¿Qué opinas sobre las últimas novedades de BoomBang?
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">145 <dfn>Topics</dfn></dd>
					<dd class="posts">2865 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by apologice
						<br />Sat Jan 11, 2014 3:01 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
	
		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=27">Tu área BB</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=49" class="forumtitle">BBox</a><br />
					Apílalas, haz que leviten, personaliza tu isla, construye estructuras increíbles. Con BBox, ¡todo es posible!
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">119 <dfn>Topics</dfn></dd>
					<dd class="posts">1315 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Maxilubo
						<br />Fri Jan 17, 2014 1:57 am</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=44" class="forumtitle">Minijuegos</a><br />
					En BB siempre hay cosas que hacer. ¿Por qué no pruebas estos Minijuegos con premios y organizados por otros usuarios?
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color: #996600;" class="username-coloured">Auro10</span>, <span style="color:#000099;">Moderadores</span>, <span style="color:#996600;">Organizadores de eventos</span>
					
				</dt>
				
					<dd class="topics">944 <dfn>Topics</dfn></dd>
					<dd class="posts">13254 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by pooo88paula
						<br />Fri Jan 17, 2014 9:39 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read_subforum.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=53" class="forumtitle">Clanes BB</a><br />
					¿Todavía no perteneces a ninguno? ¡Crea el tuyo propio!
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">1314 <dfn>Topics</dfn></dd>
					<dd class="posts">28764 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Dacono
						<br />Fri Jan 17, 2014 9:34 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=18" class="forumtitle">Intercambios</a><br />
					Seguro que encuentras a alguien que tiene lo que tú quieres.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">3789 <dfn>Topics</dfn></dd>
					<dd class="posts">12172 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by kender
						<br />Fri Jan 17, 2014 9:15 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=19" class="forumtitle">Ideas</a><br />
					Aquí puedes proponer tus ideas para mejorar BoomBang.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">2418 <dfn>Topics</dfn></dd>
					<dd class="posts">18257 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Temperance.
						<br />Fri Jan 17, 2014 2:05 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=24" class="forumtitle">Guías y tutoriales</a><br />
					¿Eres nuevo en BoomBang y necesitas alguna pista? ¿Eres un usuario experimentado y quieres compartir tus trucos e ideas con los recién llegados?
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">668 <dfn>Topics</dfn></dd>
					<dd class="posts">4103 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by kender
						<br />Fri Jan 17, 2014 3:52 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=17" class="forumtitle">Fanart</a><br />
					Comparte tus diseños y videos basados en el mundo BoomBang. ¡Da rienda suelta a tu imaginación!
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">2876 <dfn>Topics</dfn></dd>
					<dd class="posts">22177 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by maarqiitos
						<br />Fri Jan 17, 2014 6:47 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
	
		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=23">Offtopic</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=33" class="forumtitle">Informática</a><br />
					Haz tus consultas, y otros compartirán sus conocimientos contigo.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">549 <dfn>Topics</dfn></dd>
					<dd class="posts">3174 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by MiNiNaZh
						<br />Fri Jan 17, 2014 7:07 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=34" class="forumtitle">Diseño gráfico y animación</a><br />
					¿Cuáles son tus trucos de artista? ¿Cómo está la actualidad del sector?
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">3846 <dfn>Topics</dfn></dd>
					<dd class="posts">43036 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Dacono
						<br />Fri Jan 17, 2014 9:33 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=36" class="forumtitle">Beluga</a><br />
					En Beluga puedes hablar de todo lo demás.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">2919 <dfn>Topics</dfn></dd>
					<dd class="posts">29770 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by elbarbieken
						<br />Fri Jan 17, 2014 8:52 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
	
		<div class="forabg">
			<div class="inner"><span class="corners-top"><span></span></span>
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=28">Temas Técnicos</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/boombang/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
				
					<a href="./viewforum.php?f=16" class="forumtitle">Avisos de Bugs y problemas técnicos</a><br />
					Ayúdanos a identificar errores. Usa este foro cuando te encuentres con un error en BoomBang.<br />Antes de dar tu primer aviso de bugs, asegúrate de leer la guía de cómo avisar bien de un bug.
					
						<br /><strong>Moderators:</strong> <span style="color: #000099;" class="username-coloured">GKAgua</span>, <span style="color: #000099;" class="username-coloured">Sekum</span>, <span style="color: #000099;" class="username-coloured">irinsus</span>, <span style="color:#000099;">Moderadores</span>
					
				</dt>
				
					<dd class="topics">1746 <dfn>Topics</dfn></dd>
					<dd class="posts">8989 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by MiNiNaZh
						<br />Fri Jan 17, 2014 7:11 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>
	<h3>Who is online</h3>
	<p>In total there are <strong>58</strong> users online :: 15 registered, 5 hidden and 38 guests (based on users active over the past 10 minutes)<br />Most users ever online was <strong>325</strong> on Sun Nov 17, 2013 2:13 pm<br /> <br />Registered users: 1000p.f, <span style="color: #9E8DA7;" class="username-coloured">Alexa [Bot]</span>, apologice, daniel-cuki, daniu8765, <span style="color: #9E8DA7;" class="username-coloured">Google [Bot]</span>, <span style="color: #9E8DA7;" class="username-coloured">Google Adsense [Bot]</span>, Imagin3, <span style="color: #9E8DA7;" class="username-coloured">MSNbot Media</span>, muauwapa1, Ninfito, pooo88paula, Rapis10, RARE365, spark
	<br /><em>Legend: <span style="color:#FFCC00">Administrators</span>, <span style="color:#00AA00">Global moderators</span>, <span style="color:#000099">Moderadores</span>, <span style="color:#996600">Organizadores de eventos</span></em></p>

	<h3>Birthdays</h3>
	<p>Congratulations to: <strong>ZoomGuay (27), sofi.171 (14), zsasha (13), sonchian (2)</strong></p>

	<h3>Reputation Toplist</h3>
	<p>We are proud with: <strong><a href="./memberlist.php?mode=viewprofile&amp;u=2153699">colourfull</a> (810), <a style="color:#000099" href="./memberlist.php?mode=viewprofile&amp;u=3239610">GKAgua</a> (805), <a href="./memberlist.php?mode=viewprofile&amp;u=5231100">conicz</a> (671), <a href="./memberlist.php?mode=viewprofile&amp;u=5128745">sommiatruites</a> (513), <a href="./memberlist.php?mode=viewprofile&amp;u=2557221">qeri78</a> (467), <a href="./memberlist.php?mode=viewprofile&amp;u=5864045">tuh.alba</a> (436), <a style="color:#dc60b6" href="./memberlist.php?mode=viewprofile&amp;u=5121004">Sara018</a> (432), <a href="./memberlist.php?mode=viewprofile&amp;u=3063069">josetv</a> (422), <a href="./memberlist.php?mode=viewprofile&amp;u=4802703">3L-54N71</a> (412), <a href="./memberlist.php?mode=viewprofile&amp;u=4502496">ronaldvr</a> (405)</strong></p>

	<h3>Statistics</h3>
	<p>Total posts <strong>291604</strong> &bull; Total topics <strong>33052</strong> &bull; Total members <strong>43525</strong> &bull; Our newest member <strong>malira</strong></p>
</div>


<div class="forabg">
	<div class="inner"><span class="corners-top"><span></span></span>
		<ul class="topiclist">
			<li class="header">
				<dl class="icon">
					<dt>Advertisement</dt>
				</dl>
			</li>
		</ul>
		<div style="padding: 5px 5px 2px 5px; font-size: 1.1em; background-color: #ECF1F3; margin: 0px auto; text-align: center;">
			<script type="text/javascript"><!--
google_ad_client = "ca-pub-7789983817835592";
/* Adsense big footer */
google_ad_slot = "5322563876";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
		</div>
	<span class="corners-bottom"><span></span></span></div>
</div>


<div id="page-footer">

	<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist">
			<li class="icon-home"><a href="./index.php" accesskey="h">Board index</a></li>
				
			<li class="rightside">All times are UTC </li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a>&reg; Forum Software &copy; phpBB Group
		<br /><br />User Reputation MOD powered by <a href="http://www.phpbbmods.org/" title="">www.phpBBmods.org</a>
	</div>
	
	<div class="copyright" style="text-align: center; margin-top: 5px;">Advertisements by <a href="http://www.lithiumstudios.org/">Advertisement Management</a></div>

</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	
</div>

</body>
</html>